# Generated by Django 3.0.8 on 2020-07-06 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Experience', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('cv', models.ImageField(upload_to='apply/')),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('apply_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('apply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
