# Generated by Django 3.0.8 on 2020-07-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_apply_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_job',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
