# Generated by Django 3.0.8 on 2020-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200707_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
