# Generated by Django 3.0.8 on 2020-07-12 11:53

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200707_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
