# Generated by Django 3.0.8 on 2020-07-12 12:34

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200712_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='location_city',
        ),
        migrations.AddField(
            model_name='job',
            name='location_country',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
