# Generated by Django 3.0.8 on 2020-07-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20200712_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Deadline',
            field=models.DateTimeField(help_text='Example : 2002-12-29'),
        ),
    ]
