# Generated by Django 3.0.8 on 2020-07-12 10:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200711_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Example : +20 the number', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Example : +20 the number', max_length=128, null=True, region=None),
        ),
    ]
